# Generated by Django 4.2 on 2023-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="demo_link",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="source_link",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
